### PR TITLE
Correction of generator freq.

### PR DESCRIPTION
**Pull request by vblack**
Previously generator freq was 2 times lower that shown. I fix it, and because of this change generator freq's for all analog modes.
Max analog generator freq now is 25kHz.

Signed-off-by: vblack orion13@ua.fm

### CODE REVIEW

**Comment by pmos69** [comment]
Don't have time to look into it this week, but are you using the right SYS?
The APP is supposed to be used with SYS 1.50 1.6 from Marco Sinatti. Some changes in Marco's SYS affect the frequency generator.

**Comment by vblack** [comment]
Hm, never think about wrong SYS.. I'm using  SYS_B152.zip from http://www.seeedstudio.com/forum/viewtopic.php?f=22&t=1929
I will retry with Marco's SYS and come back with results...

**Comment by pmos69** [comment]
No problem.
I just remembered marco discussing this issue in the forum:
http://www.seeedstudio.com/forum/viewtopic.php?p=11362#p11362

**Comment by vblack** [comment]
Thank you, checked with SYS 1.50 1.6 from Marco Sinatti, and generator works perfect. My fault :)

**Comment by pmos69** [comment]
No worries, there are a lot more bugs to keep everyone busy :)

**Pull request closed without merging**
